import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import Navbar from "../components/Navbar";
import { Bricolage_Grotesque } from "next/font/google";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "@/context/AuthContext";
import { getUserServerSide } from "@/lib/getUserServerSide";

const bricolage = Bricolage_Grotesque({
  subsets: ["latin"],
  variable: "--font-bricolage",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ✅ Now an async function so we can get user server-side
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getUserServerSide();

  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${bricolage.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider initialUser={user}>
          <Navbar />
          {children}
          <Toaster
            position="top-center"
            toastOptions={{
              duration: 3000,
              style: {
                borderRadius: "10px",
                background: "#fffaf3",
                color: "#1a1a1a",
                fontFamily: "Bricolage Grotesque",
              },
            }}
          />
        </AuthProvider>
      </body>
    </html>
  );
}